name: tests

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: "0 12 * * 0" # run once a week on Sunday

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
        plone:
          - "6.0.0a2"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Plone ${{ matrix.plone }} with Python ${{ matrix.python }}
        uses: plone/setup-plone@v1.0.0
        with:
          python-version: ${{ matrix.python }}
          plone-version: ${{ matrix.plone }}
      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            **/eggs
            **/downloads
          key: ${{ runner.os }}-cache-${{ hashFiles('setup.*', '*.cfg') }}-${{ matrix.config[0] }}
          restore-keys: |
            ${{ runner.os }}-cache-
      - name: Install package
        run: |
          make VENV=off install

      - name: Run tests
        run: |
          make VENV=off test-ignore-warnings
