name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
        plone:
          - "6.0.0b3"
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@v1

      - name: Setup Plone ${{ matrix.plone }} with Python ${{ matrix.python }}
        uses: plone/setup-plone@v1.0.0
        with:
          python-version: ${{ matrix.python }}
          plone-version: ${{ matrix.plone }}

      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            **/eggs
            **/downloads
          key: ${{ runner.os }}-cache-${{ hashFiles('setup.*', '*.cfg') }}-${{ matrix.config[0] }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Install package
        run: |
          make VENV=off install

      - name: Run Lint
        run: |
          make VENV=off lint

      - name: Run tests
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          sleep 2
          export ROBOT_BROWSER=headlesschrome &
          make VENV=off test-ignore-warnings
